"""auto migration

Revision ID: 6dacc047213a
Revises: eb51792bc4e6
Create Date: 2026-09-19 20:48:38.912275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dacc047213a'
down_revision: Union[str, Sequence[str], None] = 'eb51792bc4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_interactions', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('survey_interactions', sa.Column('completed', sa.Boolean(), nullable=False))
    op.alter_column('survey_interactions', 'answers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.add_column('surveys', sa.Column('type', sa.Enum('web', 'whatsapp', 'whatsapp_test', name='surveytypes'), nullable=False))
    op.add_column('surveys', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.add_column('surveys', sa.Column('end_date', sa.DateTime(), nullable=False))
    op.add_column('surveys', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('surveys', sa.Column('end_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'end_message')
    op.drop_column('surveys', 'is_active')
    op.drop_column('surveys', 'end_date')
    op.drop_column('surveys', 'start_date')
    op.drop_column('surveys', 'type')
    op.alter_column('survey_interactions', 'answers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('survey_interactions', 'completed')
    op.drop_column('survey_interactions', 'start_time')
    # ### end Alembic commands ###
